site_name: doorbell
#theme: readthedocs

# mkdocs.yml
theme:
  name: "material"

nav:
    - Home: index.md
#    - Installation: installation.md
    - Code Reference:
        - Doorbell: doorbell-reference.md
        - Interfaces: interfaces-reference.md
        - MQTT-Transport: mqtt_transport-reference.md
        - Rpi: rpi_interface-reference.md
        - Transport: transport_interface-reference.md


plugins:
  - search
  - mkdocstrings